### ISSUE TITLE
Travis.org closing

### ISSUE THREAD

**Issue by bcvery1** [Fontinalis/fonet#7]
Please be aware of the following warning on Travis.org:
```
Please be aware travis-ci.org will be shutting down by end of May 2021. Please consider migrating to travis-ci.com.
```

**Comment by Fontinalis** [comment]
Yes, thanks, just noticed as well. Removing Travis and updating the current GitHub workflow to use go 1.16 would be a good way of making sure the builds are passing. We already have the GitHub Action, just need to update it. 

Personally, I like the idea of staying in GitHub as much as we can.

**Comment by Fontinalis** [comment]
@bcvery1 Just pushed the changes mentioned. Also made a new release with all of the contributions you made.. thank you so much for that. 🙂 

May I ask if you are using this package and if so, in what area?

**Comment by bcvery1** [comment]
Oh great, the new test coverage is a good idea!

I've been wanting to use this on a project at work which would estimate time left in a known process (example: image manipulation). Inputs would be values such as:
 - vCPU count
 - Averge vCPU speed
 - RAM in bytes
 - RAM speed
and the outcome would be time in seconds. This however has not been possible due to #2 . I did put work towards it with the activation functions PR a while ago, but I forget how far the repo is from making it possible.

In a personal project (which I can't go into specifics about), I'm using it to predict one of three outputs (actions) based on a stream of data, the result being a stream of actions lagging behind the inputs.

Some inspiration has come from watching `Code Bullet` on YouTube (I'm in no way affiliated with the channel), but generally I just enjoying contributing to the repo!
